# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_audio": "core.ipynb",
         "makedir": "core.ipynb",
         "blow_chunks": "chunkadelic.ipynb",
         "process_one_file": "spectro_fu.ipynb",
         "main": "spectro_fu.ipynb",
         "is_silence": "core.ipynb",
         "get_accel_config": "core.ipynb",
         "HostPrinter": "core.ipynb",
         "save": "core.ipynb",
         "n_params": "core.ipynb",
         "freeze": "core.ipynb",
         "Mish_func": "core.ipynb",
         "Mish": "core.ipynb",
         "Swish_func": "core.ipynb",
         "Swish": "core.ipynb",
         "PadCrop": "datasets.ipynb",
         "PhaseFlipper": "datasets.ipynb",
         "FillTheNoise": "datasets.ipynb",
         "RandPool": "datasets.ipynb",
         "NormInputs": "datasets.ipynb",
         "Mono": "datasets.ipynb",
         "Stereo": "datasets.ipynb",
         "RandomGain": "datasets.ipynb",
         "MultiStemDataset": "datasets.ipynb",
         "stf_up": "spectro_fu.ipynb",
         "embeddings_table": "viz.ipynb",
         "proj_pca": "viz.ipynb",
         "pca_point_cloud": "viz.ipynb",
         "print_stats": "viz.ipynb",
         "spectrogram_image": "viz.ipynb",
         "audio_spectrogram_image": "viz.ipynb",
         "tokens_spectrogram_image": "viz.ipynb",
         "plot_jukebox_embeddings": "viz.ipynb"}

modules = ["chunkadelic.py",
           "core.py",
           "data.py",
           "spectro_fu.py",
           "viz.py"]

doc_url = "https://drscotthawley.github.io/aeiou/"

git_url = "https://github.com/drscotthawley/aeiou/tree/master/"

def custom_doc_links(name): return None
